# -*- coding: utf-8 -*-
"""fruits.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16_ICkjVVMlal_IirZKiPl92zSAbNmTbh
"""

import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

import io
from tensorflow import keras
import numpy as np
from PIL import Image
from flask import Flask, request, jsonify

# Load model
model = keras.models.load_model('final.h5')
label = ["Apel","Anggur","Buah Naga","Ceri", "Durian", "Jambu Biji","Jeruk", "Kiwi", "Lemon", "Mangga", "Nanas", "Pir","Pisang", "Semangka", "Stroberi" ]

descriptions = {
    'Apel' : 'Apel adalah buah yang memiliki kulit berwarna merah, hijau, atau kuning. Dagingnya renyah dan memiliki rasa manis hingga asam. Apel kaya akan serat dan vitamin C.',
    'Anggur' : 'Anggur adalah buah yang tumbuh dalam tandan dan memiliki berbagai warna seperti hijau, merah, ungu, atau hitam. Rasanya manis dan segar. Anggur kaya akan antioksidan.',
    'Buah Naga' : 'adalah buah eksotis dengan kulit berwarna merah atau kuning dan daging putih atau merah. Rasanya sedikit manis dan memiliki banyak biji kecil berwarna hitam. Buah Naga kaya akan vitamin C dan serat.',
    'Ceri' : 'adalah buah kecil dengan warna merah cerah atau kuning. Rasanya manis dan sedikit asam. Ceri kaya akan vitamin C dan antioksidan.',
    'Durian' : 'adalah buah khas Asia Tenggara dengan kulit berduri tajam dan aroma yang sangat kuat. Dagingnya berwarna kuning cerah, bertekstur lembut, dan memiliki rasa manis yang unik. Durian kaya akan vitamin C dan serat.',
    'Jambu Biji' : 'adalah buah dengan daging berwarna putih atau merah muda. Rasanya manis dan sedikit sepat. Jambu Biji kaya akan vitamin C.',
    'Jeruk' : 'adalah buah dengan kulit berwarna oranye dan daging yang bersegmen. Rasanya asam atau manis, tergantung varietasnya. Jeruk kaya akan vitamin C.',
    'Kiwi' : 'Kiwi adalah buah kecil dengan kulit berbulu berwarna hijau atau coklat. Dagingnya berwarna hijau cerah dengan biji-biji kecil berwarna hitam. Rasanya asam dan segar. Kiwi kaya akan vitamin C dan serat.',
    'Lemon' : 'Lemon adalah buah dengan kulit berwarna kuning cerah dan daging yang asam. Lemon sering digunakan sebagai perasa dalam makanan dan minuman. Lemon kaya akan vitamin C.',
    'Mangga' : 'Mangga adalah buah dengan kulit berwarna kuning, hijau, atau merah. Dagingnya berwarna kuning oranye dan memiliki rasa manis. Mangga kaya akan vitamin A dan C.',
    'Nanas' : 'Nanas adalah buah tropis dengan bentuk memanjang dan kulit yang bersisik. Dagingnya berwarna kuning dan memiliki rasa manis dan sedikit asam. Nanas kaya akan enzim bromelain.',
    'Pir' : 'Pir adalah buah dengan bentuk bulat atau lonjong dan kulit yang berwarna hijau atau kuning. Dagingnya renyah dan memiliki rasa manis. Pir kaya akan serat.',
    'Pisang' : 'Pisang adalah buah dengan kulit berwarna kuning saat matang. Dagingnya lembut dan memiliki rasa manis. Pisang kaya akan kalium.',
    'Semangka' : 'Semangka adalah buah besar dengan kulit berwarna hijau belang putih. Dagingnya berwarna merah atau kuning dan memiliki banyak biji. Rasanya manis dan menyegarkan. Semangka kaya akan air.',
    'Stroberi' : 'Stroberi adalah buah kecil dengan bentuk hati dan berwarna merah cerah. Rasanya manis dan sedikit asam. Stroberi kaya akan vitamin C.'
}

def predict_label(img):
    i = np.asarray(img) / 255.0
    i = i.reshape(1, 384, 384, 3)
    pred = model.predict(i)
    result_label = label[np.argmax(pred)]
    result_accuracy = np.max(pred) * 100  # Convert to percentage
    return result_label, result_accuracy